language: node_js
sudo: false
node_js:
  - "0.12"
before_script:
  - npm install -g jspm
  - npm install -g karma-cli
  - jspm config registries.github.auth $JSPM_AUTH
  - jspm install
script:
  - karma start --single-run
